version: 2.1

jobs:
  vault_auth:
    docker:
      - image: vault:1.9.3
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          command: |
            export VAULT_NAMESPACE=admin
            export TAG=0.1.${CIRCLE_BUILD_NUM}
            export IMAGE_NAME=$CIRCLE_PROJECT_REPONAME
            echo $VAULT_ROLE_ID > vault/role-id
            echo $VAULT_SECRET_ID	> vault/secret-id
            vault agent -config=vault/agent.hcl
            source vault/dockerhub
            echo $DOCKER_LOGIN
            echo $DOCKER_PWD
      - persist_to_workspace:
          root: /tmp
          paths:
            - "*"
workflows:
  build_test:
    jobs:
      - vault_auth
           
